name: Test on PR

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test on PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Build Labda package
        run: |
          sh scripts/build_lambda_package.sh

      - name: IaC Apply
        env:
          COMMAND_IAC: terraform
        run: |
          cd infraestructure
          $COMMAND_IAC init
          $COMMAND_IAC validate
          $COMMAND_IAC plan
